# Generated by Django 4.1.7 on 2023-04-04 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_country', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_province', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direcciones.country')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('postal_code', models.IntegerField(primary_key=True, serialize=False)),
                ('name_location', models.CharField(max_length=50)),
                ('provinde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direcciones.province')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Localities',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=225)),
                ('number', models.IntegerField()),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('apartment', models.CharField(blank=True, max_length=3, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direcciones.location')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
